# Generated by Django for NetBox MPTT optimization

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dcim', '0215_rackreservation_status'),
    ]

    operations = [
        # Region MPTT indexes
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='dcim_region_tree_idx'),
        ),
        # SiteGroup MPTT indexes
        migrations.AddIndex(
            model_name='sitegroup',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='dcim_sitegroup_tree_idx'),
        ),
        # Location MPTT indexes
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='dcim_location_tree_idx'),
        ),
        # DeviceRole MPTT indexes
        migrations.AddIndex(
            model_name='devicerole',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='dcim_devicerole_tree_idx'),
        ),
        # Platform MPTT indexes
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='dcim_platform_tree_idx'),
        ),
    ]
