# Generated by Django 5.2.8 on 2025-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0133_make_cf_minmax_decimal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_inventoryitem_tree_id975c'),
        ),
        migrations.AddIndex(
            model_name='inventoryitemtemplate',
            index=models.Index(fields=['tree_id', 'lft'], name='dcim_inventoryitemtemplatedee0'),
        ),
    ]
