# Generated by Django for NetBox MPTT optimization

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wireless', '0015_extend_wireless_link_abs_distance_upper_limit'),
    ]

    operations = [
        # WirelessLANGroup MPTT indexes
        migrations.AddIndex(
            model_name='wirelesslangroup',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='wireless_wlangroup_tree_idx'),
        ),
    ]
