# Generated by Django for NetBox MPTT optimization

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tenancy', '0020_remove_contactgroupmembership'),
    ]

    operations = [
        # TenantGroup MPTT indexes
        migrations.AddIndex(
            model_name='tenantgroup',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='tenancy_tenantgroup_tree_idx'),
        ),
        # ContactGroup MPTT indexes
        migrations.AddIndex(
            model_name='contactgroup',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='tenancy_contactgroup_tree_idx'),
        ),
    ]
